/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
Use DataWareHouse_Analitics 
Go 
--Find total customers by countries
Select 
country,
COUNT(customer_key) As total_customers
From [gold.dim_customers]
Group by country
Order by total_customers Desc

--Find total customers by genders
Select 
gender,
COUNT(customer_key) As total_customers
From [gold.dim_customers]
Group by gender
Order by total_customers Desc

--Find total products by category
Select 
category,
COUNT(product_key) As total_products
From [gold.dim_products]
Group by category
Order by total_products Desc

--What is average costs in each category?
Select 
category,
Avg(cost) As avg_costs
From [gold.dim_products]
Group by category
Order by avg_costs Desc

--What is the total revenue generated for each category?
Select 
p.category,
Sum(f.sales_amount) As total_revenue
From [gold.fact_sales] f
Left Join [gold.dim_products] p
on p.product_key=f.product_key
Group by p.category
Order by total_revenue Desc

--What is the total revenue generated by each customer?
Select 
c.customer_key,
c.first_name,
c.last_name,
Sum(f.sales_amount) As total_revenue
From [gold.fact_sales] f
Left Join [gold.dim_customers] c
on c.customer_key=f.customer_key
Group by c.customer_key,c.first_name,c.last_name
Order by total_revenue Desc

--What is the distribution itmes across countries?

Select 
c.country,
Sum(f.quantity) As total_sold_items
From [gold.fact_sales] f
Left Join [gold.dim_customers] c
on c.customer_key=f.customer_key
Group by c.country
Order by total_sold_items Desc